import "./globals.css";
import Nav from "./components/Nav.js";
import Footer from "./components/Footer.js";
export const metadata = {
  title: "next-blog-1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='min-h-screen flex flex-col'>
    <Nav />
    <div className='flex-1'>
      {children}
    </div>
    <Footer />
  </body>
    </html>
  );
}
